# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pretty Okay
email: trent@pretty-okay.com
description: The personal website of Trent Willis, a maker of internet things. Blogging and speaking about the tech industry, web development, and living in Silicon Valley.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pretty-okay.com" # the base hostname & protocol for your site
twitter_username: trentmwillis
github_username: trentmwillis

# Build settings
markdown: kramdown
future: true
plugins:
  - jekyll-sitemap
